apiVersion: v2
name: loki-distributed
description: Helm chart for Grafana Loki in microservices mode
type: application
appVersion: 1.6.1
version: 0.10.0
home: https://github.com/unguiculus/loki-helm-chart
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
maintainers:
  - name: unguiculus
