apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  loki.yaml: |
    {{- tpl .Values.loki.config . | nindent 4 }}
