{{- with .Values.gateway.basicauth }}
{{- if and .enabled (not .existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki.gatewayFullname" $ }}
  labels:
    {{- include "loki.gatewayLabels" $ | nindent 4 }}
stringData:
  {{- if $.Values.canary.enabled }}
  username: {{ .username }}
  password: {{ .password }}
  {{- end }}
  .htpasswd: |
    {{- htpasswd (required "'gateway.basicauth.username' is required" .username) (required "'gateway.basicauth.password' is required" .password) | nindent 4 }}
{{- end }}
{{- end }}
