{{- with .Values.gateway }}
{{- if and (and .basicAuth.enabled (not .basicAuth.existingSecret)) .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki.gatewayFullname" $ }}
  labels:
    {{- include "loki.gatewayLabels" $ | nindent 4 }}
stringData:
  .htpasswd: |
    {{- htpasswd (required "'gateway.basicAuth.username' is required" .basicAuth.username) (required "'gateway.basicAuth.password' is required" .basicAuth.password) | nindent 4 }}
{{- end }}
{{- end }}
