loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
      chunk_idle_period: 30m
      chunk_encoding: snappy
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_burst_size_mb: 20
      ingestion_rate_mb: 10

    schema_config:
      configs:
        - from: 2020-09-15
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            period: 168h

    storage_config:
      boltdb:
        directory: /var/loki/index
      filesystem:
        directory: /var/loki/chunks
      index_queries_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedIndexQueriesFullname" . }}
          service: http

    chunk_store_config:
      max_look_back_period: 0
      chunk_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedChunksFullname" . }}
          service: http
      write_dedupe_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedIndexWritesFullname" . }}
          service: http

    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 30m
      cache_results: true
      results_cache:
        max_freshness: 10m
        cache:
          memcached_client:
            consistent_hash: true
            host: {{ include "loki.memcachedFrontendFullname" . }}
            max_idle_conns: 16
            service: http
            timeout: 500ms
            update_interval: 1m

    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true

canary:
  enabled: true

memcachedExporter:
  enabled: true

memcachedChunks:
  replicas: 2
  enabled: true
  extraArgs:
    - -vv

memcachedFrontend:
  replicas: 2
  enabled: true
  extraArgs:
    - -vv

memcachedIndexQueries:
  replicas: 2
  enabled: true
  extraArgs:
    - -vv

memcachedIndexWrites:
  replicas: 2
  enabled: true
  extraArgs:
    - -vv
