{{- if .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.canaryFullname" . }}
  labels:
    {{- include "loki.canaryLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3500
      targetPort: http
      protocol: TCP
  selector:
    {{- include "loki.canarySelectorLabels" . | nindent 4 }}
{{- end }}
