name: Lint Code Base

on: pull_request

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3.13.2
        env:
          FILTER_REGEX_EXCLUDE: .*(README\.md|Chart\.yaml).*
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
